// ignore_for_file: public_member_api_docs

import 'package:hive/hive.dart';

part 'task.g.dart'; // This file will be generated by Hive for type adapters

@HiveType(typeId: 1) // Unique ID for Task type with Hive
class TaskEntity extends HiveObject {
  TaskEntity({
    required this.name,
    this.isChecked = false,
    this.updatedAt,
  });
  @HiveField(0)
  late String name;

  @HiveField(1)
  late bool isChecked;

  @HiveField(2)
  final DateTime createdAt = DateTime.now();

  @HiveField(3)
  late DateTime? updatedAt;
}
